apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-landing.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "web-landing.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "web-landing.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "web-landing.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: landing
        image: {{ include "web-landing.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.app.port }}
          name: http
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.app.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.app.port }}
          initialDelaySeconds: 3
          periodSeconds: 5
