{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "stack-monolitic.fullname" . }}-ingress-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "stack-monolitic.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/api"
spec:
  ingressClassName: nginx

  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ printf "%s-%s" .Release.Name "app-monolitic" | trunc 63 | trimSuffix "-" }}
                port:
                  number: {{ index .Values "app-monolitic" "app" "port" }}
{{- end }}

