apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.mysql.port }}
      protocol: TCP
      name: mysql
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}

